<a href="https://colab.research.google.com/github/AkritiGhosh/Python_Data_Analysis/blob/main/Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing data
1. From excel
2. From CSV

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_csv = pd.read_csv('/content/sample_data/california_housing_train.csv',
                #  header = index_of_row_containing_header,
                #  sep = separator_character_default_comma
                 )

In [ ]:
df_excel = pd.read_excel('/content/sample_data/california_housing_train.xlsx',
                #  sheet_name = name_of_sheet_to_be_imported
                 )

In [3]:
df_json = pd.read_json('/content/sample_data/anscombe.json')

# Dataframe Information
1. Datatype
2. Size of df
3. List (and length) of columns
4. For each column
    1. Column name
    2. No of non-null values
    3. Data type of values in the column

In [6]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

# Print sample data
- **head(n)** - n number of data from the top. default n = 5
- **tail(n)** - n number of data from the end. default n = 5

In [26]:
df_csv.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [8]:
df_csv.tail(3)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

# Handle missing values
1. Remove the data
2. Fill the data

## Removing rows with null/na/empty

In [9]:
df_csv.dropna()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

## Fill NA/empty values with other value

In [10]:
df_csv.fillna(-1)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

# Remove duplicates

In [11]:
df_csv.drop_duplicates()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

# loc and iloc

Both are used for data selection
## iloc
uses the numeric index of row and column (eg 4th row and 5th column)

## loc
uses actual name of the row and column (e.g. 4th row in '*address*' column or '*Alice*' row in '*address*' column)

In [20]:
df_csv.iloc[5]

longitude              -114.5800
latitude                 33.6300
housing_median_age       29.0000
total_rooms            1387.0000
total_bedrooms          236.0000
population              671.0000
households              239.0000
median_income             3.3438
median_house_value    74000.0000
Name: 5, dtype: float64

In [17]:
df_csv.iloc[5,2]

29.0

In [18]:
df_csv.iloc[5,:2]

longitude   -114.58
latitude      33.63
Name: 5, dtype: float64

In [19]:
df_csv.iloc[:2]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0

In [25]:
df_csv.loc[:2,'housing_median_age']

0    15.0
1    19.0
2    17.0
Name: housing_median_age, dtype: float64

In [21]:
df_csv.loc[1]

longitude              -114.47
latitude                 34.40
housing_median_age       19.00
total_rooms            7650.00
total_bedrooms         1901.00
population             1129.00
households              463.00
median_income             1.82
median_house_value    80100.00
Name: 1, dtype: float64

In [23]:
df_csv.loc[:,'population']

0        1015.0
1        1129.0
2         333.0
3         515.0
4         624.0
          ...
16995     907.0
16996    1194.0
16997    1244.0
16998    1298.0
16999     806.0
Name: population, Length: 17000, dtype: float64

# Sorting

In [28]:
df_csv.sort_values(by='median_house_value', ascending=True)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
568,-117.02,36.40,19.0,619.0,239.0,490.0,164.0,2.1000,14999.0
16643,-122.74,39.71,16.0,255.0,73.0,85.0,38.0,1.6607,14999.0
16801,-123.17,40.31,36.0,98.0,28.0,18.0,8.0,0.5360,14999.0
3226,-117.86,34.24,52.0,803.0,267.0,628.0,225.0,4.1932,14999.0
7182,-118.33,34.15,39.0,493.0,168.0,259.0,138.0,2.3667,17500.0
...,...,...,...,...,...,...,...,...,...
15834,-122.42,37.81,52.0,1314.0,317.0,473.0,250.0,4.3472,500001.0
7927,-118.40,33.87,38.0,2398.0,431.0,911.0,392.0,5.2319,500001.0
3546,-117.90,33.63,28.0,2370.0,352.0,832.0,347.0,7.1148,500001.0
7924,-118.40,33.88,35.0,1060.0,191.0,444.0,196.0,8.0015,500001.0
14011,-122.04,37.26,24.0,4973.0,709.0,1692.0,696.0,7.8627,500001.0

In [29]:
df_csv.sort_values(by='median_income', ascending=False)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
7879,-118.40,34.11,32.0,5578.0,753.0,1567.0,697.0,15.0001,500001.0
5048,-118.12,34.12,52.0,2907.0,317.0,956.0,279.0,15.0001,500001.0
14697,-122.18,37.46,40.0,2529.0,293.0,831.0,258.0,15.0001,500001.0
7268,-118.34,34.08,52.0,1721.0,195.0,688.0,196.0,15.0001,500001.0
14791,-122.20,37.44,31.0,2328.0,270.0,722.0,247.0,15.0001,500001.0
...,...,...,...,...,...,...,...,...,...
10260,-119.99,36.09,23.0,333.0,92.0,198.0,55.0,0.4999,100000.0
10384,-120.19,38.07,43.0,102.0,19.0,44.0,13.0,0.4999,162500.0
4689,-118.08,34.15,28.0,238.0,58.0,142.0,31.0,0.4999,500001.0
11130,-121.01,37.65,52.0,178.0,53.0,152.0,62.0,0.4999,82500.0
16834,-123.32,40.43,15.0,661.0,146.0,131.0,57.0,0.4999,56700.0

# Grouping

In [39]:
df_min = df_csv.groupby('housing_median_age')['median_house_value'].min()
df_max = df_csv.groupby('housing_median_age')['median_house_value'].max()
df_mean = df_csv.groupby('housing_median_age')['median_house_value'].mean()
pd.merge(df_min,df_max, on='housing_median_age')

                    median_house_value_x  median_house_value_y
housing_median_age
1.0                             189200.0              191300.0
2.0                              47500.0              500001.0
3.0                              83200.0              500001.0
4.0                              42500.0              500001.0
5.0                              50000.0              500001.0
6.0                              58000.0              500001.0
7.0                              56200.0              500001.0
8.0                              22500.0              500001.0
9.0                              54200.0              500001.0
10.0                             53300.0              500001.0
11.0                             50400.0              500001.0
12.0                             40000.0              500001.0
13.0                             43000.0              500001.0
14.0                             32900.0              500001.0
15.0                             32500.0              500001.0
16.0                             14999.0              500001.0
17.0                             27500.0              500001.0
18.0                             47500.0              500001.0
19.0                             14999.0              500001.0
20.0                             32500.0              500001.0
21.0                             25000.0              500001.0
22.0                             34400.0              500001.0
23.0                             30000.0              500001.0
24.0                             32500.0              500001.0
25.0                             45500.0              500001.0
26.0                             36600.0              500001.0
27.0                             40000.0              500001.0
28.0                             40900.0              500001.0
29.0                             28300.0              500001.0
30.0                             42500.0              500001.0
31.0                             34200.0              500001.0
32.0                             43100.0              500001.0
33.0                             22500.0              500001.0
34.0                             26600.0              500001.0
35.0                             39600.0              500001.0
36.0                             14999.0              500001.0
37.0                             42100.0              500001.0
38.0                             39400.0              500001.0
39.0                             17500.0              500001.0
40.0                             43000.0              500001.0
41.0                             41800.0              500001.0
42.0                             39400.0              500001.0
43.0                             46600.0              500001.0
44.0                             48300.0              500001.0
45.0                             30000.0              500001.0
46.0                             26900.0              500001.0
47.0                             49600.0              500001.0
48.0                             48600.0              500001.0
49.0                             52000.0              500001.0
50.0                             54200.0              500001.0
51.0                             51900.0              500001.0
52.0                             14999.0              500001.0

# Unique values and count

In [3]:
df_csv['housing_median_age'].unique()

array([15., 19., 17., 14., 20., 29., 25., 41., 34., 46., 16., 21., 48.,
       31., 28., 24., 18., 30., 32., 23., 38., 35., 33., 13., 11., 10.,
        6., 12., 27., 22.,  5.,  8., 37.,  3., 44.,  2., 26.,  9.,  7.,
       36.,  4., 52., 40., 43., 42., 39., 49., 47., 50., 45., 51.,  1.])

In [4]:
df_csv['housing_median_age'].nunique()

52

# Conditional data selection

In [11]:
df_csv.loc[(df_csv['housing_median_age'] == 20.) & (df_csv['households'] > 300. )]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
20,-114.68,33.49,20.0,1491.0,360.0,1135.0,303.0,1.6395,44400.0
48,-115.51,32.99,20.0,1402.0,287.0,1104.0,317.0,1.9088,63700.0
80,-115.56,32.79,20.0,2372.0,835.0,2283.0,767.0,1.1707,62500.0
136,-116.11,33.64,20.0,1273.0,354.0,1548.0,355.0,2.0871,84700.0
178,-116.31,34.13,20.0,2352.0,556.0,1217.0,481.0,1.6063,55400.0
...,...,...,...,...,...,...,...,...,...
16793,-123.10,38.79,20.0,3109.0,712.0,1643.0,638.0,2.8344,164400.0
16794,-123.11,39.32,20.0,2745.0,504.0,1421.0,430.0,3.3431,137500.0
16855,-123.53,40.88,20.0,2680.0,599.0,918.0,345.0,2.2115,75000.0
16968,-124.17,41.76,20.0,2673.0,538.0,1282.0,514.0,2.4605,105900.0
16988,-124.21,41.75,20.0,3810.0,787.0,1993.0,721.0,2.0074,66900.0

In [14]:
df_csv.loc[(df_csv['housing_median_age'].isin([ 6., 40.]))]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
58,-115.52,32.67,6.0,2804.0,581.0,2807.0,594.0,2.0625,67700.0
175,-116.29,33.74,6.0,12991.0,2555.0,4571.0,1926.0,4.7195,199300.0
196,-116.38,34.10,6.0,2104.0,348.0,841.0,320.0,4.1458,116300.0
224,-116.46,33.82,6.0,4863.0,920.0,3010.0,828.0,3.9508,104200.0
289,-116.76,33.46,6.0,1251.0,268.0,544.0,216.0,3.0694,173400.0
...,...,...,...,...,...,...,...,...,...
16569,-122.69,38.36,6.0,5496.0,1374.0,2502.0,1189.0,2.4827,177500.0
16640,-122.73,38.37,40.0,1389.0,309.0,841.0,288.0,3.1094,183300.0
16652,-122.75,38.54,6.0,6719.0,1016.0,2699.0,997.0,5.4886,254200.0
16659,-122.76,38.52,6.0,2073.0,388.0,826.0,375.0,3.0550,224100.0
16696,-122.82,38.40,40.0,2406.0,423.0,1054.0,426.0,3.8846,215900.0